# Marina Golivets
# BiCIKL Hackathon (Sept 20-24, 2021, Meise, Belgium)
# Extract hybrid and parent taxon names from various floras


# get hybrid names from FlorKart, German SL, Pladias, Swiss Flora ----------------------------------
# Note: Reuses input data sets generated by M. Golivets within a different project
hybrids_florkart <- read_csv2(here("input_datasets/taxa_florkart.csv")) %>%
  filter(
    isHybrid == TRUE,
    taxonRank == "species"
  ) %>%
  pull(taxonName, acceptedTaxonName) %>%
  tibble(
    verbatim = .,
    source = "florkart"
    )

hybrids_gsl <- readxl::read_xlsx(here("input_datasets/GermanSL1.5_replaceID.xlsx")) %>%
  janitor::clean_names() %>%
  filter(
    str_detect(taxon_name, "×|^x |^X "),
    taxon_rank == "SPE"
  ) %>%
  mutate(
    name_author12 = gsub("-", "", name_author12),
    taxon_name = str_trim(paste(taxon_name, name_author12))
  ) %>%
  pull(taxon_name, neuer_name) %>%
  tibble(
    verbatim = .,
    source = "germansl"
  )

hybrids_pladias <- read_csv2(here("input_datasets/taxa_pladias.csv")) %>%
  filter(
    isHybrid == TRUE,
    taxonRank == "species"
  ) %>%
  pull(taxonName, acceptedTaxonName) %>%
  tibble(
    verbatim = .,
    source = "pladias"
  )

hybrids_swissflora <- readxl::read_xlsx(
  here("input_datasets/Checklist_2017_simple_version_20181017.xlsx"),
  skip = 4
) %>%
  slice(2:n()) %>%
  filter(str_detect(Taxonname, "×|^x |^X ")) %>%
  transmute(
    verbatim = Taxonname,
    source = "swissflora"
  )

# combine and edit
hybrids_floras <- bind_rows(
  hybrids_florkart, hybrids_gsl, hybrids_pladias, hybrids_swissflora
) %>%
  mutate(edited = str_replace(verbatim, "\\(purpurea × repens\\)", "purpurea × repens")) %>%
  filter(!(edited %in% c("Salix 'Americana'", "Spiraea 'Arguta'"))) %>%
  mutate(
    edited = str_remove_all(edited, "\\?") %>%
      str_replace_all(" x |×|^X ", " × ") %>%
      str_squish() %>%
      str_trim(),
    type = if_else(str_detect(edited, "^[A-Za-z]+ × |^× "), "name", "formula"),
    formula = edited %>%
      if_else(str_detect(., "^[A-Za-z]+ × |^× "), NA_character_, .),
    parent = str_split(formula, pattern = "×")
  ) %>%
  unnest(cols = "parent") %>%
  mutate(
    genus = str_extract(edited,  "\\w*"),
    parent = parent %>%
      str_squish() %>% 
      str_trim(),
    parent = case_when(
    grepl("^[a-z]", parent) ~ paste(genus, parent),
    grepl("^[A-Z]\\.", parent) ~ paste(genus, gsub("^[A-Z]\\.", "", parent)),
    TRUE ~ parent
  )) %>%
  mutate(
    parent = if_else(str_detect(edited, " x |× | X ", negate = TRUE), NA_character_, parent) %>%
      if_else(str_detect(., "× "), NA_character_, .) %>%
      if_else(str_replace_all(edited, " × ", " ") == ., NA_character_, .),
    edited = if_else(type == "name", str_replace_all(edited, c(" × " = " ×", "^× " = "×")), edited)
  ) %>%
  select(-genus, -formula) %>%
  filter(str_count(parent, pattern = " ") > 0 | is.na(parent)) %>%
  filter(edited != "Viola ×wittrockiana Viola ×wittrockiana GAMS") %>%
  distinct() %>%
  write_csv2(here("output_datasets/hybrids_floras.csv"))